import turtle
import turtledemo.colormixer

s = turtle.getscreen()

turtle.bgcolor('white')
turtle.pensize(6)
turtle.shapesize(2)
turtle.speed(2)
turtle.color('black')
turtle.begin_fill()
turtle.goto(100,0)
turtle.goto(100,100)
turtle.goto(0,100)
turtle.goto(0,0)
turtle.end_fill()
turtle.color('blue')
turtle.begin_fill()
turtle.goto(50,50)
turtle.goto(0,100)
turtle.goto(-50,50)
turtle.home()
turtle.end_fill()
turtle.color('green')
turtle.begin_fill()
turtle.goto(50,-50)
turtle.goto(100,0)
turtle.goto(50,50)
turtle.home()
turtle.end_fill()
turtle.color('pink')
turtle.begin_fill()
turtle.goto(100,100)
turtle.goto(50,150)
turtle.goto(0,100)
turtle.goto(50,50)
turtle.end_fill()
turtle.color('red')
turtle.begin_fill()
turtle.goto(100,0)
turtle.goto(150,50)
turtle.goto(100,100)
turtle.goto(50,50)
turtle.end_fill()

turtle.mainloop()